"""Kalilmod local server.

Serves the GUI (gui/) and a small JSON API over the subjects/ folder.
Standard library only - no dependencies.

Usage:  python serve.py [--port 8000] [--no-browser] [--static]

Modes:
  dynamic (default) - a live Claude Code session is teaching (the /teach-me loop):
                      free-text answers are reviewed and lessons edited live.
  static  (--static) - no live Claude (e.g. lessons generated by another LLM):
                      free-text questions are self-assessed against a reference.

API:
  GET  /api/mode                           -> {"mode": "dynamic"|"static"}
  GET  /api/subjects                       -> [{"subject", "lessons": [...]}]
  GET  /api/lesson?subject=X&lesson=F.json -> lesson file content
  GET  /api/progress?subject=X             -> progress.json content (or {})  (GUI-owned)
  POST /api/progress?subject=X             -> overwrite progress.json with body
  GET  /api/reviews?subject=X              -> reviews.json content (or {})   (Claude-owned, read-only here)
  GET  /api/wait?since=N&timeout=S         -> long-poll: blocks until an event past N, then returns
  GET  /api/teacher                        -> {"online": bool, "waiters": N}: is a live teacher listening?
  POST /api/notify                         -> GUI fires an event to wake the live teacher session

The wait/notify pair is the "wake the teacher" mechanism: the GUI fires /api/notify,
a backgrounded `curl /api/wait` in the Claude session unblocks and exits, and the exit
re-invokes Claude so it can act -- no terminal typing, no API key.

On every progress POST the server also writes .kalilmod-active.json (repo root) with the
active {subject, lesson}, so the live teacher loop can scope to the subject in use instead of scanning all.
"""
import argparse
import json
import os
import socket
import threading
import time
import webbrowser
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qs, urlparse

ROOT = os.path.dirname(os.path.abspath(__file__))
SUBJECTS_DIR = os.path.join(ROOT, "subjects")
GUI_DIR = os.path.join(ROOT, "gui")

MIME = {".html": "text/html", ".js": "text/javascript", ".css": "text/css",
        ".json": "application/json", ".png": "image/png", ".svg": "image/svg+xml"}

MODE = "dynamic"  # set from --static at startup

# --- Event bus for the "wake the teacher" mechanism -------------------------
# The GUI fires an event (POST /api/notify) whenever it needs the live Claude
# session to act (a free-text answer submitted, feedback left, content run out).
# The teacher session arms a background long-poll (GET /api/wait) that blocks
# until an event arrives, then exits -- and a backgrounded command exiting is
# what re-invokes ("excites") the Claude Code session. State is a monotonically
# growing list, so a *fresh* session with no memory can re-arm by first asking
# for the current sequence number; nothing about the loop is held in context.
_events = []                       # list of event dicts, append-only
_events_cv = threading.Condition() # guards _events and signals waiters
_waiters = 0                       # active /api/wait long-polls == teachers currently listening


def safe_subject_path(subject, filename):
    """Resolve a file inside a subject folder, refusing path traversal."""
    path = os.path.join(SUBJECTS_DIR, os.path.basename(subject), os.path.basename(filename))
    return path


_write_lock = threading.Lock()  # serialize file writes across the threaded server


def atomic_write(path, text):
    """Write text to path safely under concurrency. Because this server is
    threaded, two progress POSTs for one subject can otherwise interleave and
    leave a half-written / trailing-garbage file that no longer parses as JSON,
    which then breaks the GUI that reads it. We serialize writes with a lock
    (one writer at a time) and publish via os.replace (atomic on the same
    filesystem) so a reader always sees one complete document.

    On Windows, os.replace raises PermissionError if the destination is open
    right then (a concurrent GET reader) -- so we retry briefly, and as a last
    resort write in place rather than drop the update or crash the handler."""
    with _write_lock:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            f.write(text)
        for _ in range(10):
            try:
                os.replace(tmp, path)
                return
            except PermissionError:
                time.sleep(0.02)  # a reader has it open (Windows); let go and retry
        with open(path, "w", encoding="utf-8") as f:  # last resort: still publish the update
            f.write(text)
        try:
            os.remove(tmp)
        except OSError:
            pass


class Handler(BaseHTTPRequestHandler):
    def _send_json(self, code, obj):
        data = json.dumps(obj, ensure_ascii=False).encode("utf-8")
        self._send_bytes(code, data, "application/json")

    def _send_bytes(self, code, data, ctype):
        self.send_response(code)
        self.send_header("Content-Type", ctype + "; charset=utf-8")
        self.send_header("Content-Length", str(len(data)))
        self.end_headers()
        self.wfile.write(data)

    def do_GET(self):
        url = urlparse(self.path)
        query = parse_qs(url.query)
        if url.path == "/api/mode":
            self._send_json(200, {"mode": MODE})
        elif url.path == "/api/subjects":
            self._send_json(200, self.list_subjects())
        elif url.path == "/api/lesson":
            self.send_subject_file(query, query.get("lesson", [""])[0])
        elif url.path == "/api/progress":
            self.send_subject_file(query, "progress.json", default={})
        elif url.path == "/api/reviews":
            self.send_subject_file(query, "reviews.json", default={})
        elif url.path == "/api/wait":
            self.wait_for_event(query)
        elif url.path == "/api/teacher":
            # Is a live teacher currently listening? (>=1 active /api/wait long-poll)
            self._send_json(200, {"online": _waiters > 0, "waiters": _waiters})
        else:
            self.send_static(url.path)

    def do_POST(self):
        url = urlparse(self.path)
        query = parse_qs(url.query)
        if url.path == "/api/notify":
            self.notify_event()
            return
        if url.path != "/api/progress" or "subject" not in query:
            self._send_json(404, {"error": "unknown endpoint"})
            return
        length = int(self.headers.get("Content-Length", 0))
        body = self.rfile.read(length)
        try:
            progress = json.loads(body)
        except ValueError:
            self._send_json(400, {"error": "body is not valid JSON"})
            return
        subj = query["subject"][0]
        path = safe_subject_path(subj, "progress.json")
        atomic_write(path, json.dumps(progress, ensure_ascii=False, indent=2))
        # Record the active subject/lesson so the live teacher loop can scope to it.
        active = {"subject": os.path.basename(subj)}
        lesson = query.get("lesson", [None])[0]
        if lesson:
            active["lesson"] = os.path.basename(lesson)
        atomic_write(os.path.join(ROOT, ".kalilmod-active.json"), json.dumps(active))
        self._send_json(200, {"ok": True})

    def list_subjects(self):
        subjects = []
        if os.path.isdir(SUBJECTS_DIR):
            for name in sorted(os.listdir(SUBJECTS_DIR)):
                folder = os.path.join(SUBJECTS_DIR, name)
                if not os.path.isdir(folder):
                    continue
                lessons = sorted(f for f in os.listdir(folder)
                                 if f.startswith("lesson-") and f.endswith(".json"))
                if lessons:
                    subjects.append({"subject": name, "lessons": lessons})
        return subjects

    def send_subject_file(self, query, filename, default=None):
        if "subject" not in query or not filename:
            self._send_json(400, {"error": "missing subject/lesson parameter"})
            return
        path = safe_subject_path(query["subject"][0], filename)
        if not os.path.isfile(path):
            if default is not None:
                self._send_json(200, default)
            else:
                self._send_json(404, {"error": "not found"})
            return
        with open(path, "rb") as f:
            self._send_bytes(200, f.read(), "application/json")

    def _client_alive(self):
        """Peek at the client socket without consuming data: is the connection
        still open? A killed background curl closes its end, which we detect so
        it stops counting as a live teacher (see _waiters / /api/teacher)."""
        sock = self.connection
        try:
            sock.setblocking(False)
            try:
                return sock.recv(1, socket.MSG_PEEK) != b""  # b"" == peer closed
            except (BlockingIOError, InterruptedError):
                return True  # no data pending, but the connection is open
            except OSError:
                return False
        finally:
            try:
                sock.setblocking(True)
            except OSError:
                pass

    def wait_for_event(self, query):
        """Long-poll: block until an event past `since` exists, then return and
        let the caller (a backgrounded curl) exit. Returns on timeout too, so an
        idle listener re-arms harmlessly instead of hanging forever. While parked
        here the request counts as a live teacher (_waiters), and we re-check the
        client every 15s so a killed listener stops counting within seconds."""
        global _waiters
        try:
            since = int(query.get("since", ["0"])[0])
            timeout = float(query.get("timeout", ["300"])[0])
        except ValueError:
            self._send_json(400, {"error": "since/timeout must be numbers"})
            return
        deadline = time.monotonic() + timeout
        with _events_cv:
            _waiters += 1
        try:
            with _events_cv:
                while len(_events) <= since:
                    remaining = deadline - time.monotonic()
                    if remaining <= 0:
                        self._send_json(200, {"event": False, "seq": len(_events)})
                        return
                    _events_cv.wait(min(remaining, 15))
                    if len(_events) <= since and not self._client_alive():
                        return  # client vanished; drop silently, stop counting
                self._send_json(200, {"event": True, "seq": len(_events),
                                      "events": _events[since:]})
        finally:
            with _events_cv:
                _waiters -= 1

    def notify_event(self):
        """The GUI fires this to wake the teacher. Body is an optional event
        descriptor (e.g. {"kind": "free-answer", "subject": "...", "block": 3})."""
        length = int(self.headers.get("Content-Length", 0))
        event = {}
        if length:
            try:
                event = json.loads(self.rfile.read(length))
            except ValueError:
                self._send_json(400, {"error": "body is not valid JSON"})
                return
        event.setdefault("ts", time.time())
        with _events_cv:
            _events.append(event)
            seq = len(_events)
            _events_cv.notify_all()
        self._send_json(200, {"ok": True, "seq": seq})

    def send_static(self, path):
        if path == "/":
            path = "/index.html"
        full = os.path.normpath(os.path.join(GUI_DIR, path.lstrip("/")))
        if not full.startswith(GUI_DIR) or not os.path.isfile(full):
            self._send_json(404, {"error": "not found"})
            return
        ext = os.path.splitext(full)[1].lower()
        with open(full, "rb") as f:
            self._send_bytes(200, f.read(), MIME.get(ext, "application/octet-stream"))

    def log_message(self, fmt, *args):  # keep the terminal quiet
        pass


def main():
    parser = argparse.ArgumentParser(description="Kalilmod local server")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--no-browser", action="store_true")
    parser.add_argument("--static", action="store_true",
                        help="static mode: no live Claude session (self-assessed free-text)")
    args = parser.parse_args()

    global MODE
    MODE = "static" if args.static else "dynamic"

    server = ThreadingHTTPServer(("127.0.0.1", args.port), Handler)
    url = f"http://127.0.0.1:{args.port}/"
    print(f"Kalilmod running in {MODE} mode at {url}  (Ctrl+C to stop)")
    if not args.no_browser:
        threading.Timer(0.5, webbrowser.open, [url]).start()
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


if __name__ == "__main__":
    main()
